# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82d8692392a6eb103b048b9ef4e0d55208a9cfdb48742524ecc368fafd4e33297d3a48e0fe311a6d7ec92b84ebe5f85780a70fb7db34665d77d3a5e9946d1e39

test:
  secret_key_base: 68d093f10b34cf0bc8fb37060c483838129241d413ec192fe65e2fc7c78c0072eaa723d83fb8ba2313602649b2985f44fc546e5c4c13ebbffc280ac4f54b483c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
